// Staff Dashboard Screens - 100% Web Parity
export { default as StaffDashboardScreen } from './StaffDashboardScreen';
export { default as StaffAppointmentsScreen } from './StaffAppointmentsScreen';
export { default as StaffQueueScreen } from './StaffQueueScreen';
export { default as StaffPatientsScreen } from './StaffPatientsScreen';
export { default as StaffPatientDetailScreen } from './StaffPatientDetailScreen';
export { default as StaffDoctorsScreen } from './StaffDoctorsScreen';
export { default as StaffDoctorFormScreen } from './StaffDoctorFormScreen';
export { default as StaffBookAppointmentScreen } from './StaffBookAppointmentScreen';
export { default as StaffAppointmentDetailScreen } from './StaffAppointmentDetailScreen';
export { default as StaffEMRScreen } from './StaffEMRScreen';
export { default as StaffRegisterPatientScreen } from './StaffRegisterPatientScreen';
